#ifndef HW_STM32F4XX_TYPES_I2C_H
#define HW_STM32F4XX_TYPES_I2C_H

#include <stdint.h>
#include "hw/i2c/i2c.h"
#include "qapi/error.h"
#include "hw/sysbus.h"
#include "hw/i2c/i2c.h"
#include "qemu/timer.h"
#include "qom/object.h"

/* ==================== ENUMERATIONS ======================= */

/* stm32f4xx I2C fsm states */
typedef enum stm32f4xx_i2c_fsm_state_e
{
    STM32F4XX_I2C_DISABLED,
    STM32F4XX_I2C_IDLE,
    STM32F4XX_I2C_START,
    STM32F4XX_I2C_SENT_READ,
    STM32F4XX_I2C_SENT_WRITE,
    STM32F4XX_I2C_RECV_1BYTE,
    STM32F4XX_I2C_RECV_2BYTES_FIRST,
    STM32F4XX_I2C_RECV_2BYTES_SECOND,
    STM32F4XX_I2C_RECV_3BYTES,
    STM32F4XX_I2C_RECV_NBYTES,
    STM32F4XX_I2C_TRANSMITTING,
}stm32f4xx_i2c_fsm_state_t;

/* stm32f4xx I2C operation in execution */
typedef enum stm32f4xx_opt_e
{
    ops_na = 0, // No operation
    ops_w = 1,  // Write
    ops_r = 2,  // Read    
}stm32f4xx_opt_t;

/* ==================== DATA STRUCTURES ==================== */

/* stm32f4xx I2C fsm outputs & transitions */
typedef bool (*stm32f4xx_i2c_fsm_condition_func_t)(void*);
typedef void (*stm32f4xx_i2c_fsm_output_func_t)(void*);

/* stm32f4xx I2C fsm transition */
typedef struct stm32f4xx_i2c_fsm_trans_s
{
	stm32f4xx_i2c_fsm_state_t           org_st;     // State of origin 
	stm32f4xx_i2c_fsm_condition_func_t  condition;  // Transition Condition
	stm32f4xx_i2c_fsm_state_t           dst_st;     // Destination state
	stm32f4xx_i2c_fsm_output_func_t     output;     // Output generated by the transition
}stm32f4xx_i2c_fsm_trans_t;

/* stm32f4xx I2C fsm structure */
struct stm32f4xx_i2c_fsm_s
{
	int act_st;			                    // State where the fsm is 
  	stm32f4xx_i2c_fsm_trans_t *trans_table;	// Pointer to an array of transitions
};

/* stm32f4xx I2C parameters used in the internal logic */
typedef struct stm32f4xx_i2c_config_s
{
    uint8_t addr;
    stm32f4xx_opt_t ops;
    bool flg_sb;
    bool flg_start;
    bool flg_stop;
    bool flg_swrst;
    bool flg_addr;
}stm32f4xx_i2c_config_t;

#define TRANSITIONS (19 + 1)

#endif /* HW_STM32F4XX_TYPES_I2C_H */